/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Image;
import java.io.IOException;
import java.text.DecimalFormat;
import rollthedice.Game;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;


/**
 *
 * @author Ezra Audivano Dirfa
 */
public class GameView extends javax.swing.JFrame {

    /**
     * Creates new form GameView
     */
    Map<Integer, Integer> mode = new HashMap<Integer, Integer>();
    Game[] game = new Game[12];
    
    String inputString = "";
    int total, idx, value,  round = 0;
    int[] totalPerRoll;
    DecimalFormat df;
        
        
    public GameView() throws IOException  {
        initComponents();
        setResizable(false);
        this.setSize(800, 600);
        initHashmapModus();
        totalPerRoll = new int[12];
        df = new DecimalFormat("#.##");
        try {
            setValueDice(1,1);
        } catch (IOException ex) {
            Logger.getLogger(GameView.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.setTitle("Roll The Dice - Develop by Ezra Audivano");
    }
   
    
    public void setValueDice(int value1, int value2) throws IOException {
        Image img;
        img = ImageIO.read(getClass().getResource("image/die-"+value1+".png"));
        jLabelDiceLeft.setIcon(new ImageIcon(img));
        img = ImageIO.read(getClass().getResource("image/die-"+value2+".png"));
        jLabelDiceRight.setIcon(new ImageIcon(img));
    }
    
    public void initHashmapModus(){
        for (int i = 1; i <= 6; i++) {
            mode.put(i, 0);
        }
    }
    
    public void updateComponentUI(String amount, String total, String round){
        jLabelJumlahPoint.setText("Amount : " +amount);
        jLabelSkor.setText(total);
        jLabelRound.setText("ROUND " +round);
    }
    
  
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelGame = new javax.swing.JPanel();
        jLabelRound = new javax.swing.JLabel();
        jLabelSkor1 = new javax.swing.JLabel();
        jLabelSkor = new javax.swing.JLabel();
        jLabelJumlahPoint = new javax.swing.JLabel();
        btnRoll = new javax.swing.JButton();
        jLabelDiceLeft = new javax.swing.JLabel();
        jLabelDiceRight = new javax.swing.JLabel();
        jLabelBg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelGame.setPreferredSize(new java.awt.Dimension(800, 600));
        jPanelGame.setLayout(null);

        jLabelRound.setFont(new java.awt.Font("Gill Sans MT", 1, 48)); // NOI18N
        jLabelRound.setForeground(new java.awt.Color(255, 255, 255));
        jLabelRound.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelRound.setText("START");
        jPanelGame.add(jLabelRound);
        jLabelRound.setBounds(0, 40, 800, 50);

        jLabelSkor1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jLabelSkor1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSkor1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelSkor1.setText("Score :");
        jPanelGame.add(jLabelSkor1);
        jLabelSkor1.setBounds(650, 30, 130, 50);

        jLabelSkor.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        jLabelSkor.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSkor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelSkor.setText("0");
        jPanelGame.add(jLabelSkor);
        jLabelSkor.setBounds(650, 60, 130, 50);

        jLabelJumlahPoint.setFont(new java.awt.Font("Cascadia Code ExtraLight", 0, 18)); // NOI18N
        jLabelJumlahPoint.setForeground(new java.awt.Color(255, 255, 255));
        jLabelJumlahPoint.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelJumlahPoint.setText("Amount = 0");
        jPanelGame.add(jLabelJumlahPoint);
        jLabelJumlahPoint.setBounds(0, 290, 800, 40);

        btnRoll.setBackground(new java.awt.Color(7, 208, 164));
        btnRoll.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        btnRoll.setForeground(new java.awt.Color(255, 255, 255));
        btnRoll.setText("Roll the Dice");
        btnRoll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRollActionPerformed(evt);
            }
        });
        jPanelGame.add(btnRoll);
        btnRoll.setBounds(300, 410, 190, 61);

        jLabelDiceLeft.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/die-1.png"))); // NOI18N
        jPanelGame.add(jLabelDiceLeft);
        jLabelDiceLeft.setBounds(130, 140, 112, 111);

        jLabelDiceRight.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/die-1.png"))); // NOI18N
        jPanelGame.add(jLabelDiceRight);
        jLabelDiceRight.setBounds(550, 140, 112, 111);

        jLabelBg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/bg-1.png"))); // NOI18N
        jLabelBg.setPreferredSize(new java.awt.Dimension(800, 600));
        jPanelGame.add(jLabelBg);
        jLabelBg.setBounds(0, -340, 800, 1270);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelGame, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelGame, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRollActionPerformed
        if(round < 12){
            int id = round;
            round++;
            System.out.println("\nROUND " + round);
            
            //membuat lemparan game baru
            game[id] = new Game();
            game[id].play();
            try {
                //mengeset value dadu yang dihasilkan
                setValueDice(game[id].getResultFirstDice(), game[id].getResultSecondDice());
            } catch (IOException ex) {
                Logger.getLogger(GameView.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            //menampilkan result per lemparan di terminal
            game[id].showResultPerGame();
            
            //menghitung akumulasi total poin per lemparan
            total += game[id].getTotalValue();
            totalPerRoll[id] = game[id].getTotalValue();
            
            //mengupdate value component UI
            updateComponentUI(Integer.toString(game[id].getTotalValue()), Integer.toString(total), Integer.toString(round));
            
            if(round == 12){
                btnRoll.setText("Result");
            }
            
            if(round == 11){
                btnRoll.setText("Last Roll");
            }

            // proses menghitung modus
            idx = game[id].getResultFirstDice();
            value = mode.get(idx) + 1;
            mode.replace(idx, value);
            
            idx = game[id].getResultSecondDice();
            value = mode.get(idx) + 1;
            mode.replace(idx, value);
            
        }else {
            btnRoll.setEnabled(false);
            ResultView rv = new ResultView(totalPerRoll, mode, game, total);
            this.setVisible(false);
            rv.setVisible(true);
        }
        
    }//GEN-LAST:event_btnRollActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new GameView().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(GameView.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRoll;
    private javax.swing.JLabel jLabelBg;
    private javax.swing.JLabel jLabelDiceLeft;
    private javax.swing.JLabel jLabelDiceRight;
    private javax.swing.JLabel jLabelJumlahPoint;
    private javax.swing.JLabel jLabelRound;
    private javax.swing.JLabel jLabelSkor;
    private javax.swing.JLabel jLabelSkor1;
    private javax.swing.JPanel jPanelGame;
    // End of variables declaration//GEN-END:variables
}
